### ISSUE TITLE
Http Code 418

### ISSUE THREAD

**Issue by msieurtoph** [prettymuchbryce/node-http-status#18]
You are missing the most important http code, man : 

* HTTP 418 : "I am a teapot"

Seriously, I was using this funny http code for unit testing... and my test broke when I tried to use your module ... 
Not too bad, but I am missing my 418. 
:)

**Comment by prettymuchbryce** [comment]
Good call. It should probably be here. Would you like to open a PR to add it? If not – I can get to it soon.

**Comment by msieurtoph** [comment]
Done! :) 
https://github.com/prettymuchbryce/node-http-status/pull/19

Glad to contribute!

**Comment by msieurtoph** [comment]
Since the merge has been approuved, I close the issue.
