### ISSUE TITLE
Code completion removed by improved minification

### ISSUE THREAD

**Issue by rhmeeuwisse** [prettymuchbryce/node-http-status#9]
My IDE does no longer offer code completion for the HTTP status code identifiers, only getStatusText() is suggested. For example:

    HttpStatus = require('http-status-codes');

    response.status(HttpStatus.    <== code completion only showing 'getStatusText()'
    
This makes me sad, as I have to look up the code identifiers again and have to type more (without typos). No doubt is the 'improve minification' commit an improvement, however it's also a regression.

My preference is code completion over minification but perhaps there is a win-win?

**Comment by prettymuchbryce** [comment]
Hey rhmeeuwisse. Sorry for the delay. I understand the frustration here. Can I ask which IDE you are using ? Is this still happening.

**Comment by rhmeeuwisse** [comment]
Hah! Thanks for asking me to check again, code completion is working properly now. 

I'm using WebStorm 10.0.4 now which has "reworked support for JavaScript from the ground up". When I opened this issue I was on the then current WebStorm 9.

Thanks for your time.

**Comment by prettymuchbryce** [comment]
Good to hear it. Thanks for taking time to check, and sorry again for the delay.
